name: pdl_p
channels:
  - fastai
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - fastai
  - nbdev
  - gradio
  - python-graphviz
  - numba
  - pip
  - pip:
    - fastcore
    - transformers
    - diffusers
    - datasets
    - torcheval
    - timm
    - -e .

