name: pdl_gpu
channels:
  - pytorch
  - nvidia
  - fastai
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - jupyter
  - fastai
  - nbdev
  - gradio
  - python-graphviz
  - numba
  - pip
  - pip:
    - fastcore
    - transformers
    - diffusers
    - datasets
    - torcheval
    - timm
    - accelerate
    - -e .

